### ISSUE TITLE
Possible EventEmitter memory leak detected + extremly slow + not using multithread

### ISSUE THREAD

**Issue by RiccardoManzan** [codemaster138/node-threading#1]
Hi, i can't make it work.
I have to iterate a really big array, so i am doing something like this:
```js
const farm = createFarm('./file.js', {
    maxSize: 6, // As my current cpu threads
});
Promise.All(bigArray.map( async elem = > {
  let res = await (await(farm.spawn()).function(args);
  /* handling res */
})
await farm.end();
```
I am launching the app using `node --experimental-worker index.js`

This way it's *really slow*, plain iteration is way faster.
During the execution it shows multiple times per iteration the warning: 
```
(node:31664) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unlock listeners added to [WorkerInterface]. Use emitter.setMaxListeners() to increase limit
```
I tried using process.setMaxListeners(0), but as expected it didn't work (as this package should spawn other processes)
Futhermore it looks like this is not working at all, it's still using a single cpu thread (??).
Can this problem be due to Promise.all?
I'm using node 14 on ubuntu 20.10

Any thoughts?
Thanks

**Comment by codemaster138** [comment]
Hey @RiccardoManzan, thanks for reporting this issue! Can you show me what your worker looks like? This looks like it's probably an issue with your worker

**Comment by codemaster138** [comment]
I developed this on node 13, so maybe try that. In case that works, please tell me so I can upgrade for newer versions of node, otherwise, send me your worker code, like I had said.

**Comment by codemaster138** [comment]
I used node v15 in development, so tell me if _that_ works so I can integrate backwards-compatibility if it does. Also, you should try running your project with `DEBUG=subservient:* node —experimental-worker index.js` to enable debug logs, maybe those could be useful.

**Comment by codemaster138** [comment]
@RiccardoManzan As for not using multithreading properly, I am not sure whether node‘s „threading“ API actually uses CPU threads, or whether it prefers to use single-thread multi-_processing_ instead

**Comment by RiccardoManzan** [comment]
I checked-out removing all extra things to build a test project, i switched to node 15.\
My worker just had to do a very long `for` for each element of a very long array of integers (generated by another `for`).\
It looks like that:
- Node actually spawns multiple threads, the number of threads change in function of farm size. (I am checking this thing using `ps -o nlwp <process id>` )
- Node main process still uses just one cpu thread at time. - in regards of this, i am not sure this is due my code structure or if it's node fault.

Here's the code for reference:
Main async function:
```js
const bigArray = [];
for (let i = 0; i < 10000; i++) {
    bigArray.push(i);
}

const farm = createFarm('./worker.js', {
    maxSize: 2, // Maximum amount of workers
});
let res = await Promise.all(
    bigArray.map(async n => {
        let r = await (await farm.spawn()).task(n);
        console.log(r);
        return r;
    })
);
await farm.end();
```
worker file:
```js
import { expose } from 'subservient';

expose({
    task(num) {
        for (let i = 0; i < 10000; i++) {}
        return 'processed: ' + num;
    },
});
```

Anyway i'm still getting `(node:44551) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unlock listeners added to [WorkerInterface]. Use emitter.setMaxListeners() to increase limit` as output, multiple times for each iteration

**Comment by codemaster138** [comment]
@RiccardoManzan  Okay, thanks for the information. My Laptop is currently being fixed (screen broke) and I don‘t think I‘ll be a lot of help with just my phone, so I‘ll try to work this out as soon as I have it back. I hope it‘s not too big a problem for you to wait that long.

As for the thread spawning thing, I think that the way it works is that node spawns another node process for each thread, just with some additional flags to tell it it‘s a worker and somehow slaves that process to its main thread, probably through a Berkeley socket. I honestly don‘t know how it works, but if you say your main process stays single-threaded, and also because the worker code needs it’s own file, I think that‘s the way it works.

I think that a potential workaround for your problem would be to spawn your two workers outside of the loop, like this:
```js
const farm = createFarm('./worker.js', {
    maxSize: 2, // Maximum amount of workers
});
const worker1 = await farm.spawn();
const worker2 = await farm.spawn();
let res = await Promise.all(
    bigArray.map(async (n, i) => {
        let r = await (((i % 2) === 0) ? worker1 : worker2).task(n);
        console.log(r);
        return r;
    })
);
await farm.end();
```

I know it really isn‘t optimal, but I think it should solve your problem for now. Again, I‘m sorry if it takes a couple days until I can help you, and I‘ll inform you if I find out anything else.

(I‘m adding the suspended label until I get my laptop fixed)

**Comment by RiccardoManzan** [comment]
Sure, np!

**Comment by codemaster138** [comment]
Hey @RiccardoManzan sorry it took me so long, I had a lot of other things to take care of, but I think I'll have some more time for this later today.

I have read through the code and confirmed that the `Event Emitter Memory Leak` error is in fact a bug in the code. I'll try to find a fix this afternoon.

As for the problem with it being slow, did my [comment above](https://github.com/codemaster138/node-threading/issues/1#issuecomment-781888463) help you? I do think that the most likely reason for the slow speed is that you are re-running the spawn instruction on every iteration, which creates a lot of unnecessary processing overhead.

**Comment by RiccardoManzan** [comment]
Sincerely, i don't remember. I will check it out! :)

**Comment by codemaster138** [comment]
Hi @RiccardoManzan, I know it's been a long time, but I was just looking back at this repo and I'm considering making some improvements, so I just wanted to keep you up to date on this issue.

First, I should probably explain why your program is so slow when using subservient. In the main program, you created a big array of data. Now, you're looping over the array and, for each and every single item, getting a worker with `farm.spawn()` running its `worker.task()` method over and over again.

Initiating a task call is quite slow, because subservient has to send a message to the thread saying *"Hey, here's some data. Please run `worker.task` on it!"* This message-sending procedure causes a little bit of latency that just doesn't occur when you're running in single-thread, which explains your problem.

In your case, here's what you *should* be doing:

main.js
```js
...
(async () => {
  // Generate bigArray
  const bigArray = Array.from({length: 1000}, () => Math.floor(Math.random() * 40));

  // Create two workers
  const workerOne = await farm.spawn();
  const workerTwo = await farm.spawn();

  // Let worker 1 process half of the values
  const promiseOne = workerOne.task({
    numWorkers: 2,
    offset: 0,
    numbers: bigArray
  });

  // Let worker 2 process the other half
  const promiseTwo = workerTwo.task({
    numWorkers: 2,
    offset: 1,
    numbers: bigArray
  });

  // Wait for both promises to resolve
  const [result1, result2] = await Promise.all([promiseOne, promiseTwo]);

  // Put the results back together into a single array
  const result = result1.reduce((a, v, i) => a.concat([v, result2[i]]), []);

  await farm.end();
})();
...
```

Then, in worker.js:
```js
expose({
  task({
    numbers,
    numWorkers,
    offset
  }) {
    var processed = [];

    for (let i = offset; i < numbers.length; i += numWorkers) {
      for (let j = 0; j < 10000; j++) {}
      processed.push(numbers[i]);
    }

    return processed;
  },
});
```

Basically, we pass both workers _all_ of the numbers immediately in one call. Then, `workerOne` process all the even numbers and `workerTwo` processes all the odd ones. Then they each return their results and we use that big confusing `reduce` statement to combine them both back into a single array.

Of course, this can be expanded to use any amount of workers.

This approach also mitigates the EventEmitter memory leak issue because the erratic `spawn()` and `task()` calls are only performed twice each in the entire program.

However, the keep in mind that the host thread has no indication of the workers' progress, and cannot use any of the results from the workers this way. To mitigate this issue in the future, I'm planning to introduce generator tasks that can use the `yield` keyword to return values as they are being processed and can be observed by the host.

I know that you've probably moved on from this issue a long time ago, but I just wanted to put this out there for anyone who might have this problem in the future.

**Comment by RiccardoManzan** [comment]
Hi, i just found out that i didn't thanked you for your help, so thankyou and sorry for the late.
Unfortunately i didn't had the occasion to retry this, but i guess you tested that this solves the issue.
